In [ ]:
import numpy as np
class Agent():
    def __init__(self,OOXX_Index,Epsilon,Alpha):
        self.index = OOXX_Index
        self.epsilon = Epsilon
        self.alpha = Alpha
        self.value = np.zeros((3,3,3,3,3,3,3,3,3))
        self.stored_Outcome = np.zeros(9).astype(np.int8)
    def reset(self):
        self.stored_Outcome = np.zeros(9).astype(np.int8)
    def move(self,State):
        Outcome = State.copy()
        available = np.where(Outcome==0)[0]
        if np.random.binomial(1,self.epsilon):
            Outcome[np.random.choice(available)] = self.index
        else:
            temp_Value = np.zeros(len(available))
            for i in range(len(available)):
                temp_Outcome = Outcome.copy()
                temp_Outcome[available[i]] = self.index
                temp_Value[i] = self.value[tuple(temp_Outcome)]
            choose = np.argmax(temp_Value)
            Outcome[available[choose]] = self.index
        Error = self.value[tuple(Outcome)] - self.value[tuple(self.stored_Outcome)]
        self.value[tuple(self.stored_Outcome)] += self.alpha*Error
        self.stored_Outcome = Outcome.copy()
        return Outcome
    def pure_move(self,State):
        available = np.where(State==0)
        temp_Value = np.zeros(len(available))
        for i in range(len(available)):
            outcome=State.copy()
            outcome[available[0][i]]=self.index
            temp_Value[i]=self.value[tuple(outcome)]
        choice=np.argmax(temp_Value)
        print('choice',choice)
        print('available',available)
        return available[0][choice]
Agent1 = Agent(OOXX_Index = 1,Epsilon=0.1,Alpha=0.1)
Agent2 = Agent(OOXX_Index = 2,Epsilon=0.1,Alpha=0.1)

In [29]:
def Judge(Outcome,OOXX_Index):
    Triple = np.repeat(OOXX_Index,3)
    winner = 0
    if 0 not in Outcome:
        winner =3
    if (Outcome[0:3]==Triple).all() or (Outcome[3:6]==Triple).all() or (Outcome[6:9]==Triple).all():
        winner = OOXX_Index
    if (Outcome[0:7:3]==Triple).all() or (Outcome[1:8:3]==Triple).all() or (Outcome[2:9:3]==Triple).all():
        winner = OOXX_Index
    if (Outcome[0:9:4]==Triple).all() or (Outcome[2:7:2]==Triple).all():
        winner = OOXX_Index
    return winner

In [32]:
Trial = 30000
Winner = np.zeros(Trial)
for i in range(Trial):
    if i==20000:
        Agent1.epsilon = 0
        Agent2.epsilon = 0
    # if i%1000==0:
    #     print(i)
    Agent1.reset()
    Agent2.reset()
    winner = 0
    State = np.zeros(9).astype(np.int8)
    while winner == 0:
        Outcome = Agent1.move(State)
        winner = Judge(Outcome,1)
        if winner == 1:
            Agent1.value[tuple(Outcome)] = 1
            Agent2.value[tuple(State)] = -1
        elif winner == 0:
            State = Agent2.move(Outcome)
            winner = Judge(State,2)
            if winner == 2:
                Agent2.value[tuple(State)]=1 
                Agent1.value[tuple(Outcome)]=-1
    Winner[i] = winner

In [37]:
#human first
def humanfirstgame():
    state=np.array([0,0,0,0,0,0,0,0,0])
    print(state.reshape(3,3))
    while 0 in state:
        action=int(input("input your action(0-8):"))
        state[action]=1
        if Judge(state,1)==1:
            print("you win")
            return
        print(state.reshape(3,3))
        state=Agent2.move(state)
        print(state.reshape(3,3))
        if Judge(state,2)==2:
            print(state.reshape(3,3))
            print("ai win")
            return
    print('tie')
    return
humanfirstgame()

[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[0 0 0]
 [0 1 0]
 [0 0 0]]
[[2 0 0]
 [0 1 0]
 [0 0 0]]
[[2 0 1]
 [0 1 0]
 [0 0 0]]
[[2 0 1]
 [0 1 0]
 [2 0 0]]
[[2 0 1]
 [0 1 0]
 [2 0 0]]
[[2 2 1]
 [0 1 0]
 [2 0 0]]
[[2 2 1]
 [1 1 0]
 [2 0 0]]
[[2 2 1]
 [1 1 2]
 [2 0 0]]
[[2 2 1]
 [1 1 2]
 [2 0 1]]
[[2 2 1]
 [1 1 2]
 [2 2 1]]
tie
